const baseTheme = {
  spacing: {
    small: '0.85rem',
    normal: '1rem',
    large: '1.5rem',
    xlarge: '2rem',
  },
  fontSize: {
    xsmall: '0.7rem',
    small: '0.85rem',
    normal: '1rem',
    large: '1.5rem',
    xlarge: '2rem',
  },
  lineHeight: {
    xsmall: '1rem',
    small: '1.3rem',
    normal: '1.5rem',
    large: '2.3rem',
    xlarge: '3rem',
  },
  fontWeight: {
    thin: 100,
    extraLight: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semiBold: 600,
    bold: 700,
    extraBold: 800,
    black: 900,
    extraBlack: 950,
  },
  breakpoints: {
    sm: 'min-width: 576px',
    md: 'min-width: 768px',
    lg: 'min-width: 992px',
    xl: 'min-width: 1200px',
    xxl: 'min-width: 1400px',
  },
  colors: {
    backgroundPrimary: '#212121',
    backgroundSecondary: '#171717',
    borderPrimary: '#000000',
    textPrimary: '#dfdfdf',
    successBackgroundPrimary: '#00bc8b',
    warningBackgroundPrimary: '#ffc200',
    warningTextPrimary: '#000000',
    dangerBackgroundPrimary: '#ff606A',
    dangerTextPrimary: '#dfdfdf',
    dangerBackgroundSecondary: '#fa747c',
  },
};

export default baseTheme;
